### ISSUE TITLE
The hosts in istio example does not allow external access

### ISSUE THREAD

**Issue by huikang** [argoproj/rollouts-demo#11]
I install the istio example in a local k8s cluster. After installation, pointing the browser to `localhost` shows an empty page.

After applying the following changes, I can see the application page at `localhost`. Shall we fix this?

```
diff --git a/examples/istio/virtualservice.yaml b/examples/istio/virtualservice.yaml
index 148496c..00dac8c 100644
--- a/examples/istio/virtualservice.yaml
+++ b/examples/istio/virtualservice.yaml
@@ -6,8 +6,9 @@ spec:
   gateways:
   - istio-rollout-gateway
   hosts:
-  - istio-rollout.apps.argoproj.io
-  - istio-rollout.local
+  - "*"
```

**Comment by markvandenbosch** [comment]
@huikang Why is this issue closed without applying the fix?
This change would make the example usable without changing the virtual service locally.
