### ISSUE TITLE
sample particle colour

### ISSUE THREAD

**Issue by tkbits9** [argoproj/rollouts-demo#16]
Hi. 

I'm trying to run the istio example but it seems the sample app is showing multiple particles with different colours even when I just have one version of the service active. I believe at this stage it would only show one colour and then once a new canary is added a new colour would appear. 

Is there something I'm missing?

Also tried different rollouts and same result. 

Many thanks,  

<img width="950" alt="sample_app" src="https://user-images.githubusercontent.com/56674094/122687299-a0da4900-d20d-11eb-8937-a6050c3cc1f0.png">
<img width="607" alt="sample_app_watch" src="https://user-images.githubusercontent.com/56674094/122687305-a33ca300-d20d-11eb-8557-739be8d4c2d7.png">
![image](https://user-images.githubusercontent.com/56674094/122687225-388b6780-d20d-11eb-8794-09b38082e041.png)

**Comment by jessesuen** [comment]
The only difference between the backend container images (e.g. `argoproj/rollouts-demo:yellow` vs `argoproj/rollouts-demo:blue`) is an environment variable named `COLOR`. See:

https://github.com/argoproj/rollouts-demo/blob/master/Dockerfile#L15
https://github.com/argoproj/rollouts-demo/blob/master/main.go#L143-L146

When this environment variable is missing, the backend returns a random color. It seems that is what's happening in your setup.

**Comment by tkbits9** [comment]
Hi @jessesuen, thanks for this and apologies I Should've explained better. I was trying to work around the problem related to the UI not being reachable from my host machine (Win 10). 

I'm using ubuntu WSL2 with minikube. I've tried to fix it by using minikube tunnel but couldn't make it work. 

NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)   
istio-ingressgateway   LoadBalancer   10.97.57.105   127.0.0.1     15020:32525/TCP,80:30425/TCP,443:30374/TCP,15029:31560/TCP,15030:31605/TCP,15031:30789/TCP,15032:30803/TCP,15443:30416/TCP   21m

UI It's still not reachable from my host browser. 

I'm probably missing something but would appreciate any insights. 

Many thanks, 
T.

**Comment by tkbits9** [comment]
solved!
